In [1]:
import json
import numpy as np
import nltk
from nltk_utils import tokenize_fn, stem_fn ,bag_of_words

import torch
from torch.utils.data import Dataset, DataLoader
from classes import createChatDataset


[nltk_data] Downloading package punkt to /home/mkh/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/mkh/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [2]:
with open('intents.json', "r") as f:
    intents = json.load(f)


In [3]:
#tokenization -> Lower+stem --> exclude punctuation --> bag of words

In [4]:
import string
all_words = []
tags = []
xy = []
for intent in intents["intents"] :
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns'] :
        w = tokenize_fn(pattern)
        all_words.extend(w)
        xy.append((w,tag))



import nltk
import string
from nltk.corpus import stopwords


# Download NLTK stopwords
nltk.download('stopwords')

# Define stopwords, punctuation, and ignore list
stop_words =[" "] # set(stopwords.words('english'))
punctuation = set(string.punctuation)

# The ignore list containing words to exclude
ignore_list = [
    "test", "example", "random", "blah", "lorem ipsum", "qwerty", "asdf", "xyz", "123", 
    "password", "admin", "test123", "fake", "spam", "no response", "undefined", "null", 
    "help", "not available", "nothing", "undefined input", "unknown", "this is a test", 
    "demo", "irrelevant", "unsupported", "error", "fail", "sorry", "not applicable", ",", 
    ".", "!", "?", ";", ":", "-", "_", "'", "\"", "(", ")", "[", "]", "{", "}", "<", ">", 
    "&", "%", "$", "#", "@", "/", "\\", "~", "^", "*", "|", "+", "=" , "it", "'m", "a", "an", 
    "the", "are", "or", "be", "do", "I"
]

# Assuming stem_fn is defined to stem words (e.g., using nltk.stem)
from nltk.stem import PorterStemmer
stem_fn = PorterStemmer().stem

# Filter out stopwords, punctuation, and ignore list
filtered_words = [word for word in all_words if word not in stop_words and word not in punctuation and word not in ignore_list]
print(filtered_words)
# Apply stemming
all_words = [stem_fn(w) for w in filtered_words]

# Output the processed words
print(all_words)

# print(all_words)
all_words = sorted(set(all_words))
# print(all_words)
tags = sorted(set(tags))
# print(tags)   

['Hi', 'Hey', 'How', 'you', 'Is', 'anyone', 'there', 'Hello', 'Good', 'day', 'Bye', 'See', 'you', 'later', 'Goodbye', 'Thanks', 'Thank', 'you', 'That', "'s", 'helpful', 'Thank', "'s", 'lot', 'Which', 'items', 'you', 'have', 'What', 'kinds', 'of', 'items', 'there', 'What', 'you', 'sell', 'Do', 'you', 'take', 'credit', 'cards', 'Do', 'you', 'accept', 'Mastercard', 'Can', 'pay', 'with', 'Paypal', 'Are', 'you', 'cash', 'only', 'How', 'long', 'does', 'delivery', 'take', 'How', 'long', 'does', 'shipping', 'take', 'When', 'get', 'my', 'delivery', 'Tell', 'me', 'joke', 'Tell', 'me', 'something', 'funny', 'Do', 'you', 'know', 'joke']
['hi', 'hey', 'how', 'you', 'is', 'anyon', 'there', 'hello', 'good', 'day', 'bye', 'see', 'you', 'later', 'goodby', 'thank', 'thank', 'you', 'that', "'s", 'help', 'thank', "'s", 'lot', 'which', 'item', 'you', 'have', 'what', 'kind', 'of', 'item', 'there', 'what', 'you', 'sell', 'do', 'you', 'take', 'credit', 'card', 'do', 'you', 'accept', 'mastercard', 'can', 'pay'

[nltk_data] Downloading package stopwords to /home/mkh/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
print(len(xy) , "patterns \n" )
print(len(tags), "tags:\n", tags)
print(len(all_words),"all words:\n", all_words)

26 patterns 

7 tags:
 ['delivery', 'funny', 'goodbye', 'greeting', 'items', 'payments', 'thanks']
52 all words:
 ["'s", 'accept', 'anyon', 'are', 'bye', 'can', 'card', 'cash', 'credit', 'day', 'deliveri', 'do', 'doe', 'funni', 'get', 'good', 'goodby', 'have', 'hello', 'help', 'hey', 'hi', 'how', 'is', 'item', 'joke', 'kind', 'know', 'later', 'long', 'lot', 'mastercard', 'me', 'my', 'of', 'onli', 'pay', 'paypal', 'see', 'sell', 'ship', 'someth', 'take', 'tell', 'thank', 'that', 'there', 'what', 'when', 'which', 'with', 'you']


In [6]:
## bag of the words 
# create training data
X_train = []
y_train = [] 

for (pattern_sentence , tag) in xy:
    print(pattern_sentence)
    bag =  bag_of_words(pattern_sentence, all_words)
    print(bag)
    X_train.append(bag)

    label = tags.index(tag)
    y_train.append(label) # for calculate the loss_fn -- CreossEntropy
    classes = tags 

['Hi']
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
['Hey']
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
['How', 'are', 'you']
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.]
['Is', 'anyone', 'there', '?']
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0.]
['Hello']
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
['Good', 'day']
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [7]:
X_train = np.array(X_train)
y_train = np.array(y_train)

X_train,  y_train

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]], dtype=float32),
 array([3, 3, 3, 3, 3, 3, 2, 2, 2, 6, 6, 6, 6, 4, 4, 4, 5, 5, 5, 5, 0, 0,
        0, 1, 1, 1]))

### Create the data set

In [8]:

train_dataset = createChatDataset(X_train,y_train,classes)

print(len(train_dataset))


26


In [9]:
train_dataset.classes

['delivery', 'funny', 'goodbye', 'greeting', 'items', 'payments', 'thanks']

In [10]:
y_train

array([3, 3, 3, 3, 3, 3, 2, 2, 2, 6, 6, 6, 6, 4, 4, 4, 5, 5, 5, 5, 0, 0,
       0, 1, 1, 1])

In [11]:
torch.save(train_dataset, "train_dataset.pt")

In [12]:
print("done")

done
